<?php
/**
 * @file
 * This module is developed for getting quiz informations from quizlet.com.
 *
 * TODOS: 
 * - Add Option to Create Multiple Instances of Same Vocabulary List IDs
 */
/**
* Implementation of hook_init()
* 
*/
function quizlet_init() {
  drupal_add_css(drupal_get_path('module', 'quizlet') .'/css/quizlet.css'); 
  drupal_add_js(drupal_get_path('module', 'quizlet') .'/js/quizlet.js'); 
  if (arg(0) == 'node' && arg(1) == 'add' && arg(2) == 'quizlet') {
    drupal_goto('quizlet/search');
  }
}
/**
* Implementation of hook_help()
*/
function quizlet_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#quizlet':
      return t('General settings for drupal.');
  }
}
/**
* implementation of hook_perm()
* 
*/
function quizlet_perm() {
  return array('administrator quizlet', 'quizlet search', 'quizlet save', 'create quizlet content', 'delete own quizlet content', 'delete any quizlet content', 'edit any quizlet content', 'edit own quizlet content', 'view flashcards');
}
/**
 * Implementation of hook_access().
 */
function quizlet_access($op, $node, $account) {
  switch ($op) {
    case 'create':
      return user_access('create quizlet content', $account) ? TRUE : NULL;
    case 'update':
      return user_access('edit any quizlet content', $account) || (user_access('edit own quizlet content', $account) && ($node->uid == $account->uid)) ? TRUE : NULL;
    case 'delete':
      return user_access('delete any quizlet content', $account) || (user_access('delete own quizlet content', $account) && ($node->uid == $account->uid)) ? TRUE : NULL;
  }
}
/**
* implementation of hook_menu()
* 
*/
function quizlet_menu() {
  $items['admin/settings/quizlet'] = array(
    'title' => t('Quizlet Settings'),
    'description' => t('Quizlet Settings Page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quizlet_api_form'),
    'access arguments' => array('administrator quizlet'),
    'file' => 'quizlet.module',
  );
  $items['admin/settings/quizlet/keys'] = array(
    'title' => 'Quizlet Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/settings/quizlet/token'] = array(
    'title' => t('Quizlet Token'),
    'description' => t('Quizlet Token'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quizlet_api_token_form'),
    'access arguments' => array('administrator quizlet'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'quizlet.module',
  );
  $items['quizlet/search'] = array(
    'title' => t('Quizlet Search'),
    'description' => t('Quizlet Search Page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quizlet_search_form'),
    'access arguments' => array('quizlet search'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'quizlet.module',
  );
  $items['quizlet'] = array(
    'title' => t('Quizlet Saved Lists'),
    'description' => t('Quizlet Lists Page'),
    'page callback' => 'quizlet_lists',
    'access arguments' => array('quizlet search'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'quizlet.module',
  );
  $items['quizlet/list/%'] = array(
    'title' => t('Quizlet Lists'),
    'description' => t('Quizlet Lists Page'),
    'page callback' => 'quizlet_term_lists',
    'page arguments' => array(2),
    'access arguments' => array('quizlet search'),
    'type' => MENU_CALLBACK,
    'file' => 'quizlet.module',
  );
  $items['quizlet/save/%'] = array(
    'title' => t('Quizlet Save'),
    'description' => t('Quizlet Lists Save'),
    'page callback' => 'quizlet_terms_save',
    'page arguments' => array(2),
    'access arguments' => array('quizlet save'),
    'type' => MENU_CALLBACK,
    'file' => 'quizlet.module',
  );
  $items['node/%node/learn'] = array(
    'title' => t('Learn'),
    'description' => t('Learn page'),
    'page callback' => 'quizlet_terms_embeddedcards',
    'page arguments' => array(1, 2),
    'access callback' => 'quizlet_flashcards_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'quizlet.module',
  );
  $items['node/%node/scatter'] = array(
    'title' => t('Scatter'),
    'description' => t('Scatter page'),
    'page callback' => 'quizlet_terms_embeddedcards',
    'page arguments' => array(1, 2),
    'access callback' => 'quizlet_flashcards_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'quizlet.module',
  );
  $items['node/%node/flashcards'] = array(
    'title' => t('Flashcards'),
    'description' => t('Flashcard page'),
    'page callback' => 'quizlet_terms_embeddedcards',
    'page arguments' => array(1, 2),
    'access callback' => 'quizlet_flashcards_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'quizlet.module',
  );
  $items['quizlet/group'] = array(
    'title' => t('Quizlet Group'),
    'description' => t('Quizlet Group'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quizlet_group_form'),
    'access arguments' => array('quizlet group'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'quizlet.module',
  );
  $items['quizlet/group/list/%'] = array(
    'title' => t('Quizlet Group Lists'),
    'description' => t('Quizlet Group Lists Page'),
    'page callback' => 'quizlet_group_term_lists',
    'page arguments' => array(3),
    'access arguments' => array('quizlet search'),
    'type' => MENU_CALLBACK,
    'file' => 'quizlet.module',
  );
  $items['quizlet/group/save/%'] = array(
    'title' => t('Quizlet Group Save'),
    'description' => t('Quizlet Group Lists Save'),
    'page callback' => 'quizlet_group_terms_save',
    'page arguments' => array(3),
    'access arguments' => array('quizlet save'),
    'type' => MENU_CALLBACK,
    'file' => 'quizlet.module',
  );
  return $items; 
} 
/**
* Settings API key form
* 
* @param mixed $form_state
*/
function quizlet_api_form($form_state = array()) {
  $form['api_key'] = array(
    '#type' => 'fieldset',
    '#title' => t('Developer Key'),
  );
  $form['api_key']['quizlet_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Quizlet Client ID'),
    '#required' => TRUE,
    '#default_value' => variable_get('quizlet_api_key', ''),
    '#description' => t('Quizlet Client ID.'),
  );
  $form['api_key']['quizlet_secret_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret Key'),
    '#required' => TRUE,
    '#default_value' => variable_get('quizlet_secret_key', ''),
    '#description' => t('Secret Key.'),
  );
  $form['visiblity'] = array(
    '#type' => 'fieldset',
    '#title' => t('Search Visibility Settings'),
  );
  $form['visiblity']['quizlet_show_creator'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Creator'),
    '#default_value' => variable_get('quizlet_show_creator', ''),  
  );
  $form['visiblity']['quizlet_show_date_created'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Date Created'),
    '#default_value' => variable_get('quizlet_show_date_created', ''),  
  );
  $form['visiblity']['quizlet_show_last_modified'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Last Modified'),
    '#default_value' => variable_get('quizlet_show_last_modified', ''),  
  );
  $form['quizlet_multiple_copy'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow Creating Multiple Copies of Same Quizlet Vocabulary List'),
    '#default_value' => variable_get('quizlet_multiple_copy', ''),  
  );
  return system_settings_form($form);
}
/**
* Quizlet Search Form
* 
* @param mixed $form_state
*/
function quizlet_search_form($form_state = array(), $page=1) {
  global $user;
  $key = variable_get('quizlet_api_key', '');
  $token = variable_get('quizlet_access_token', ''); 
  $keywords = $_GET['keywords'];
  $has_images = $_GET['has_images'] ? TRUE : FALSE;
  $sort =  $_GET['sort'] ? $_GET['sort'] : '';
  $criteria = '';
  if ($_GET['page']) {
    $criteria .= '&page='. ($_GET['page']+1);
  } 
  if ($has_images) {
    $criteria .= '&images_only=on';
  }
  if ($sort) {
    $criteria .= '&sort='. $sort; 
  }  
  $url = 'https://api.quizlet.com/2.0/search/sets?client_id='. $key .'&q='. str_replace(' ', '+', $keywords) .'&whitespace=off'. $criteria; 
  if ($keywords) {
    $response = json_decode(quizlet_api_request($url, $token), TRUE);
    if (!$response) {
      drupal_set_message(t("Cannot communicate to server. Please try again."), 'warning'); 
    }
    else {
      $form_state['storage']['data'] = $response['sets'];
      $form_state['storage']['keywords']  = $keywords;
      $form_state['storage']['has_images']  = $has_images; 
      $form_state['storage']['sort'] = $sort;
    }
  }
  $form['keywords'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Keyword'),
    '#required' => TRUE,
    '#default_value' => $form_state['storage']['keywords'],
    '#description' => t('Enter keyword to search on quizlet.'),
    '#size' => ($page ? 60 : 25),
  );
  $form['has_images'] = array(
    '#type' => 'checkbox',
    '#title' => t('Only Show Lists with Images'),
    '#default_value' => $form_state['storage']['has_images'],
  );
  $options = array('most_recent' => t('Most Recent'), 'alphabetical' => t('Alphabatical'), 'most_studied' => t('Most Studied'));
  $form['sort'] = array(
    '#type' => 'radios',
    '#title' => t('Sort By'),
    '#options' => $options,
    '#default_value' => $form_state['storage']['sort'],
  );
  $form['search'] = array(
    '#type' => 'submit',
    '#title' => t('Search'),
    '#value' => t('Search'),
  );
  if (!empty($form_state['storage']['data'])) {
    $header = array(t('Title'), t('Term Count'));
    if (variable_get('quizlet_show_creator', '')) {
      $header[] = t('Creator'); 
    }
    if (variable_get('quizlet_show_date_created', '')) {
      $header[] = t('Created'); 
    }
    if (variable_get('quizlet_show_last_modified', '')) {
      $header[] = t('Last Modified'); 
    }
    if (user_access('quizlet save', $user)) {
      $header[] =  t('Save'); 
    }
    $rows = array();
    foreach ($form_state['storage']['data'] as $key => $value) {
      $row = array();
      $row[] = l(htmlspecialchars_decode($value['title'], ENT_QUOTES), 'quizlet/list/'. $value['id'], array('query' => 'keywords='. $form_state['storage']['keywords'] . $criteria));
      $row[] = $value['term_count'];  
      if (variable_get('quizlet_show_creator', '')) { 
        $row[] = $value['created_by'];
      }
      if (variable_get('quizlet_show_date_created', '')) { 
        $row[] = date('m-d-Y H:i', $value['created_date']); 
      } 
      if (variable_get('quizlet_show_last_modified', '')) {   
        $row[] = date('m-d-Y H:i', $value['modified_date']);
      }
      $nid = db_result(db_query("select nid from {quizlet_lists} where quizlet_id='%d'", $value['id']));       
      if (user_access('quizlet save', $user) && !variable_get('quizlet_multiple_copy', '')) { 
        $row[] = l(($nid ? t('Update') : t('Save')), 'quizlet/save/'. $value['id'], array('query' => 'keywords='. $form_state['storage']['keywords'] . $criteria));
      }
      else {
        $row[] = l(($nid ? t('Save New Copy') : t('Save')), 'quizlet/save/'. $value['id'], array('query' => 'keywords='. $form_state['storage']['keywords'] . $criteria));       
      }
      $rows[] = $row;
    }
    if (!empty($rows)) {
      $output = theme('table', $header, $rows); 
      global $pager_page_array, $pager_total;
      $pager_total[0] = ceil($response['total_results']/30);
      $pager_page_array[0] = isset($_GET['page']) ? $_GET['page'] : 0;
      $output .= theme('pager', 30);
    }
    else {
      $output = t('No results found.');
    }
  }
  elseif (!empty($form_state['storage']['keywords'])) {
    $output = t('No results found.');  
  }
  $output .= quizlet_powered_by(); 
  if ($page) {
    $form['data'] = array(
      '#type' => 'item',
      '#value' => $output
    );
  }
  $form['#method'] = 'GET';
  $form['#action'] = url('quizlet/search');
  return $form;
}
function quizlet_search_form_submit($form, &$form_state) {
  $key = variable_get('quizlet_api_key', '');
  $token = variable_get('quizlet_access_token', ''); 
  $keywords = $form_state['values']['keywords'];
  $has_images = $_GET['has_images'] ? TRUE : FALSE;
  $url = 'https://api.quizlet.com/2.0/search/sets?client_id='. $key .'&q='. str_replace(' ', '+', $keywords) .'&whitespace=off';
  if ($keywords) {
    $response = json_decode(quizlet_api_request($url, $token), TRUE);
    if (!$response) {
      drupal_set_message(t("Cannot communicate to server. Please try again."), 'warning'); 
    }
    else {
      $form_state['storage']['data'] = $response['sets'];
      $form_state['storage']['keywords']  = $keywords;
      $form_state['storage']['has_images']  = $has_images; 
    }
  }
}
/**
* Sending API Request
* 
* @param mixed $url
* @param mixed $token
*/
function quizlet_api_request($url, $token) {
  $curl = curl_init($url);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Bearer '. $token));
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  $json = curl_exec($curl);
  curl_close($curl);
  if ($json) {
    return $json;
  }
  else {
    return FALSE;
  }
}
/**
* Getting term lists
* 
* @param mixed $id
*/
function quizlet_term_lists($id) {
  $criteria = '';
  if ($_GET['page']) {
    $criteria .= '&page='. ($_GET['page']+1);
  } 
  if ($_GET['has_images']) {
    $criteria .= '&images_only=on';
  }
  if ($_GET['sort']) {
    $criteria .= '&sort='. $_GET['sort']; 
  }
  $key = variable_get('quizlet_api_key', ''); 
  $token = variable_get('quizlet_access_token', ''); 
  $url = 'https://api.quizlet.com/2.0/sets/'. $id .'?client_id='. $key .'&extended=on&whitespace=off';
  $backlink = l(t('Back to search results'), 'quizlet/search', array('query' => 'keywords='. $_GET['keywords'] . $criteria));
  $nid = db_result(db_query("select nid from {quizlet_lists} where quizlet_id='%d'", $id));       
  $savelink = l(($nid ? t('Update this list') : t('Save this list')), 'quizlet/save/'. $id, array('query' => 'keywords='. $_GET['keywords'] . $criteria));
  if (!$response = json_decode(quizlet_api_request($url, $token), TRUE)) {
    drupal_set_message(t("Cannot communicate with server"), 'error');
    return $backlink;
  }
  else {
    $rows = array();
    $header  = array();
    foreach ($response['terms'] as $key => $value) {
      $row = array();
      foreach ($value as $k => $v) {
        if ($k == 'image') {
          if ($v['url']) {
            $row[] = '<img src="'. $v['url'].'" height="'. $v['height'].'" width="'. $v['width'] .'">';
          }
          else {
            $row[] = '';
          }
        }
        else {
          $row[] = $v;   
        }
      }
      $rows[] = $row;
    }
    return theme_render_template(
            drupal_get_path('module', 'quizlet') .'/templates/quizlet_list.tpl.php', 
            array(
             'title' => $response['title'],
             'description' => $response['description'],
             'term_count' => $response['term_count'],
             'terms' => theme('table', $header, $rows),
             'backlink' => $backlink,
             'savelink' => $savelink 
           ));
   }  
}
/**
* Implementation of hook_node_info().
*/
function quizlet_node_info() {
  return array(
    'quizlet' => array(
      'name' => t('Quizlet List'),
      'module' => 'quizlet',
      'description' => t("Custom content type to store quizlet lists"),
      'has_title' => TRUE,
      'title_label' => t('Title'),
      'body_label' => t('Description'),
      'has_body' => TRUE,
    ),
    'quizlet_private' => array(
      'name' => t('Quizlet Private'),
      'module' => 'quizlet_private',
      'description' => t("Custom content type to store quizlet group lists"),
      'has_title' => TRUE,
      'title_label' => t('Title'),
      'body_label' => t('Description'),
      'has_body' => TRUE,
    )
  );
}
/**
* Implementation of hook_form().
*/
function quizlet_form(&$node, $form_state) {
  $type = node_get_types('type', $node);
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -5
  );
  $form['body'] = array(
    '#type' => 'textarea',
    '#title' => check_plain($type->body_label),
    '#default_value' => $node->body,
    '#required' => FALSE
  );
  $form['quizlet_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Quizlet ID'),
    '#default_value' => $node->quizlet_id,
    '#required' => TRUE,
    '#access' => FALSE,
  );
  $form['quizlet_data'] = array(
    '#type' => 'textarea',
    '#title' => t('Quizlet Data'),
    '#default_value' => $node->quizlet_data,
    '#required' => FALSE,
    '#prefix' => '<div style="display:none;">',
    '#suffix' => '</div>',
  );
  $form['filter'] = filter_form($node->format);
  return $form;
}
//Quizlet Private List
function quizlet_private_form(&$node, $form_state) {
  return quizlet_form($node, $form_state);
}
/**
 * Implementation of hook_load().
 */
function quizlet_load($node) {
  global $user;
  $quizlet = db_fetch_object(db_query("SELECT quizlet_id, quizlet_data FROM {quizlet_lists} WHERE nid = %d", $node->nid));
  return $quizlet;
}
//Quizlet Private List
function quizlet_private_load($node) {
  global $user;
  $quizlet = db_fetch_object(db_query("SELECT quizlet_id, quizlet_data FROM {quizlet_private_lists} WHERE nid = %d", $node->nid));
  return $quizlet;
}
/**
 * Implementation of hook_insert().
 */
function quizlet_insert($node) {
  db_query("INSERT INTO {quizlet_lists} (nid, quizlet_id, quizlet_data) VALUES ('%d', '%d', '%s')", $node->nid, $node->quizlet_id, $node->quizlet_data);
}
//Quizlet Private List Insert
function quizlet_private_insert($node) {
  db_query("INSERT INTO {quizlet_private_lists} (nid, quizlet_id, quizlet_data) VALUES ('%d', '%d', '%s')", $node->nid, $node->quizlet_id, $node->quizlet_data);
}
/**
 * Implementation of hook_update().
 */
function quizlet_update($node) {
  db_query("UPDATE {quizlet_lists} SET quizlet_data = '%s' WHERE nid = '%d'", $node->quizlet_data, $node->nid);
}
//Quizlet Private List Update
function quizlet_private_update($node) {
  db_query("UPDATE {quizlet_private_lists} SET quizlet_data = '%s' WHERE nid = '%d'", $node->quizlet_data, $node->nid);
}
/**
 * Implementation of hook_delete().
 */
function quizlet_delete($node) {
  db_query("DELETE FROM {quizlet_lists} WHERE nid = %d", $node->nid);  
}
function quizlet_private_delete($node) {
  db_query("DELETE FROM {quizlet_private_lists} WHERE nid = %d", $node->nid);  
}
/**
 * Implementation of hook_view().
 *
 * @param $block
 */
function quizlet_view($node, $teaser = FALSE, $page = FALSE, $block = FALSE) {
  global $user;
  $node = node_prepare($node, $teaser);
/* Remove Display of Quizlet ID 
 * TODO: Add as a setting option
  $node->content['quizlet_id'] = array(
    '#value' => '<b>Quizlet ID:</b><br>'. $node->quizlet_id .'<br>', 
    '#weight' => 1,
  );
*/
  $quizlet_data = unserialize($node->quizlet_data);
  $rows = array();
  $header  = array();
  foreach ($quizlet_data as $key => $value) {
    $row = array();
    foreach ($value as $k => $v) {
      if ($k == 'image') {
        if ($v['url']) {
          $row[] = '<img src="'. $v['url'].'" height="'. $v['height'].'" width="'. $v['width'] .'">';
        }
        else {
          $row[] = '';
        }
      }
      else {
        $row[] = $v;   
      }
    }
    $rows[] = $row;
  }
  $output = theme('table', $header, $rows); 
  $node->content['quizlet_data'] = array(
    '#value' => '<div class="quizet_list"><div class="quizlet_terms_title"><b>'. t('Terms') .' : </b><a href="javascript:void(0);" id="quizlet_images">Hide Images</a></div>' . $output .'</div>'. drupal_get_form('quizlet_selection_cards', $node) . quizlet_powered_by(), 
    '#weight' => 3,
  );
  return $node;
}
//Quizlet Private List View
function quizlet_private_view($node, $teaser = FALSE, $page = FALSE, $block = FALSE) {
  return quizlet_view($node, $teaser = FALSE, $page = FALSE, $block = FALSE);
}
/**
* Save quizlet lists
* 
* @param mixed $id
*/
function quizlet_terms_save($id) {
  global $user;
  $criteria = '';
  if ($_GET['page']) {
    $criteria .= '&page='. ($_GET['page']+1);
  } 
  if ($_GET['has_images']) {
    $criteria .= '&images_only=on';
  }
  if ($_GET['sort']) {
    $criteria .= '&sort='. $_GET['sort']; 
  }
  $key = variable_get('quizlet_api_key', ''); 
  $token = variable_get('quizlet_access_token', ''); 
  $url = 'https://api.quizlet.com/2.0/sets/'. $id .'?client_id='. $key .'&extended=on&whitespace=off';
  
  if (!$response = json_decode(quizlet_api_request($url, $token), TRUE)) {
    drupal_set_message(t("Cannot communicate with server"), 'error');
    drupal_goto('quizlet/search', 'keywords='. $_GET['keywords'] . $criteria);
  }
  else {
    $nid = db_result(db_query("select nid from {quizlet_lists} where quizlet_id='%d'", $id));
    if ($nid && !variable_get('quizlet_multiple_copy', '')) {
      $node = node_load($nid);
      $node->changed = time();
      $node->title = htmlspecialchars_decode($response['title'], ENT_QUOTES);
      $node->body = $response['description'];
      $node->quizlet_data = serialize($response['terms']);
      $node->quizlet_id = $id;
      node_save($node);
      drupal_set_message(t('Quizlet list updated successfully.'));
    }
    else {
      $node = new stdClass();
      $node->type = 'quizlet';
      $node->status = 1;
      $node->uid = $user->uid;
      $node->created = time();
      $node->changed = time();
      $node->title = htmlspecialchars_decode($response['title'], ENT_QUOTES);
      $node->body = $response['description'];
      $node->quizlet_data = serialize($response['terms']);
      $node->quizlet_id = $id;
      node_save($node);
      drupal_set_message(t('Quizlet list saved successfully.'));  
    }
    drupal_goto('node/'. $node->nid);  
  }
}
/**
* Saved lists
* 
*/
function quizlet_lists() {
  global $user;
  drupal_set_title(t('Most Recently Saved Quizlet Vocabulary Lists'));
  $sql = "select nid from {node} where type='quizlet'";
  $cnt_sql = "select count(*) from {node} where type='quizlet'";
  $header = array(array('data' => t('Title'), 'field' => 'title'), array('data' => t('Created'), 'field' => 'created', 'sort' => 'desc'), array('data' => t('Changed'), 'field' => 'changed'));
  if (user_access('delete any quizlet content', $user)) {
    $header[] =  t('Delete'); 
  }
  $sql .= tablesort_sql($header); 
  $query = pager_query($sql, 30, 0, $cnt_sql);
  $rows = array();
  while ($result = db_fetch_object($query)) {
    $row = array();
    $node = node_load($result->nid); 
    $row[] = l($node->title, 'node/'. $result->nid);
    $row[] = date('m-d-Y H:i', $node->created);   
    $row[] = date('m-d-Y H:i', $node->changed);
    if (user_access('delete any quizlet content', $user)) {  
      $row[] = l(t('Delete'), 'node/'. $node->nid .'/delete', array('query' => 'destination=quizlet')); 
    }
    $rows[] = $row;
  }
  $output = theme('table', $header, $rows);
  $output .= theme('pager', 30);
  $output .= quizlet_powered_by();
  return $output;
}
/**
* Powered by Quizlet
*/
function quizlet_powered_by() {
  return '<div class="quizlet_link"><a href="http://quizlet.com/"><b>Powered by Quizlet.com</b></a></div>';
}
/**
* Access to flashcard nodes
* 
* @param mixed $node
*/
function quizlet_flashcards_access($node) {
  global $user;
  if ($node->type == 'quizlet' && user_access('view flashcards', $user)) {
    return TRUE;  
  }
	elseif ($node->type == 'quizlet_private'  && user_access('view flashcards', $user)) {
	  return TRUE;
	}
  else {
    return FALSE; 
  }
}
/**
* Quizlet embedded charts
* 
* @param mixed $node
* @param mixed $type
*/
function quizlet_terms_embeddedcards($node, $type) {
  if ($type=='learn') {
    $url = 'http://quizlet.com/'. $node->quizlet_id .'/learn/embedv2/?hideLinks';  
    $height = 480;
  }
  elseif ($type=='scatter')   {
    $url = 'http://quizlet.com/'. $node->quizlet_id .'/scatter/embedv2/?hideLinks';  
    $height = 520; 
  }
  else {
	  $url = 'http://quizlet.com/'. $node->quizlet_id .'/familiarize/embedv2/?hideLinks';  
    $height = 350;
  }
  return theme_render_template(drupal_get_path('module', 'quizlet') .'/templates/embedded_cards.tpl.php', array('url' => $url, 'height' => $height));
}
/**
* Selection of cards
* 
* @param mixed $form_state
* @param mixed $node
*/
function quizlet_selection_cards($form_state = array(), $node) {
  $flashcard = url('node/'. $node->nid .'/flashcards', array('absolute' => TRUE));
  $learn = url('node/'. $node->nid .'/learn', array('absolute' => TRUE));
  $scatter = url('node/'. $node->nid .'/scatter', array('absolute' => TRUE));
  $options = array('' => t('Please select'), $flashcard => t('Flashcard'), $learn => t('Learn'), $scatter => t('Scatter'));
  $form['select_card'] = array(
    '#type' => 'select', 
    '#title' => t('Select card'),
    '#options' => $options,
  );
  return $form;
}
/**
* Implementation of hook_block() Keyword Search Block
* 
* @param mixed $op
* @param mixed $delta
* @param mixed $edit
*/
function quizlet_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Search Vocabulary Lists by Keyword'), 
      'cache' => BLOCK_CACHE_PER_ROLE | BLOCK_CACHE_PER_PAGE, 
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => t('Keyword Search for Vocabulary Lists'), 
          'content' => drupal_get_form('quizlet_search_form', 0),
        );
        break;
    }
    return $block;
  }
}
/**
* Quizlet API get token form
* 
* @param mixed $form_state
*/
function quizlet_api_token_form($form_state = array()) {
  $clientid = variable_get('quizlet_api_key', '');
  $secretkey = variable_get('quizlet_secret_key', ''); 
  if (empty($clientid) || empty($secretkey)) {
    form_set_error('', 'Please enter client id and secret key first.'); 
    drupal_goto('admin/settings/quizlet');
  }
  $accesstoken = variable_get('quizlet_access_token', '');
  $siteurl = url('admin/settings/quizlet/token', array('absolute' => TRUE)); 
  $authorizeUrl = "https://quizlet.com/authorize/?client_id={$clientid}&response_type=code&scope=read%20write_set";
  $tokenUrl = 'https://api.quizlet.com/oauth/token';
  if (empty($_GET['code']) && empty($_GET['error']) && empty($accesstoken)) {
    $_SESSION['state'] = md5(mt_rand().microtime(true));    
    $form['path'] = array(
      '#type' => 'item',
      '#value' => '<a href="'.$authorizeUrl.'&state='.$_SESSION['state'].'&redirect_uri='. $siteurl .'">Authorize Site First</a>'
    );
  }
  if (!empty($_GET['error'])) { // An error occurred authorizing
    form_set_error('path', 'Error:' . $_GET['error']);
  }
  if (empty($accesstoken) && $_GET['code']) { 
    $payload = array(
      'code' => $_GET['code'],
      'redirect_uri' => $siteurl,
      'grant_type' => 'authorization_code'
    );
    $curl = curl_init($tokenUrl);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_USERPWD, "{$clientid}:{$secretkey}");
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $payload);
    $token = json_decode(curl_exec($curl), true);
    $responseCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
    curl_close($curl);
     
    if ($responseCode != 200) { // An error occurred getting the token
      form_set_error('path', 'Error:' . $token['error']); 
    }
  }
  $form['quizlet_access_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Token'),
    '#default_value' => variable_get('quizlet_access_token', $token['access_token']),
    '#required' => TRUE,
    '#attributes' => array('readonly' => 'readonly'),
  );
  return system_settings_form($form); 
}
/**
* Group search form
* 
* @param mixed $form_state
*/
function quizlet_group_form($form_state = array()) {
  global $user;
  $token = variable_get('quizlet_access_token', '');
  $group_id = $_GET['group_id']; 
  $url = 'https://api.quizlet.com/2.0/groups/'. $group_id .'/sets';	
  if ($group_id) {
    $response = json_decode(quizlet_api_request($url, $token), TRUE);
    if (!$response) {
      drupal_set_message(t("Cannot communicate to server. Please try again."), 'warning'); 
    }
    else {
      $form_state['storage']['group_id'] = $group_id;
      $form_state['storage']['data'] = $response;
    }
  }
  $form['group_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Group ID'),
    '#required' => TRUE,
    '#default_value' => $form_state['storage']['group_id'],
    '#description' => t('Enter group id to get data'),
  );
  $form['search'] = array(
    '#type' => 'submit',
    '#title' => t('Search'),
    '#value' => t('Search'),
  );
  if (!empty($form_state['storage']['data'])) {
    $header = array(t('Title'), t('Term Count'), t('Save'));
    $rows = array();
    foreach ($form_state['storage']['data'] as $key => $value) {
      $row = array();
			$row[] = l($value['title'], 'quizlet/group/list/'. $value['id'], array('query' => 'group_id='.$group_id));
			$row[] = $value['term_count'];
			$row[] = l('Save', 'quizlet/group/save/'. $value['id'],  array('query' => 'group_id='.$group_id));
      $rows[] = $row;
    }
    if (!empty($rows)) {
      $output = theme('table', $header, $rows); 
    }
    else {
      $output = t('No results found.');
    }
  }
  elseif (!empty($form_state['storage']['group_id'])) {
    $output = t('No results found.');  
  }
	$form['data'] = array(
		'#type' => 'item',
		'#value' => $output
	);
  $form['#method'] = 'GET';
  $form['#action'] = url('quizlet/group');
  return $form;
}
/**
* Show quizlet group list details
* 
* @param mixed $set_id
*/
function quizlet_group_term_lists($set_id) {
  $key = variable_get('quizlet_api_key', ''); 
  $token = variable_get('quizlet_access_token', '');
  $url = 'https://api.quizlet.com/2.0/sets/'. $set_id .'?client_id='. $key .'&extended=on&whitespace=off';
  $backlink = l(t('Back to group'), 'quizlet/group', array('query' => 'group_id='. $_GET['group_id']));
  $nid = db_result(db_query("select nid from {quizlet_private_lists} where quizlet_id='%d'", $set_id));       
  $savelink = l(($nid ? t('Update this list') : t('Save this list')), 'quizlet/group/save/'. $set_id, array('query' => 'group_id='. $_GET['group_id'] . $criteria));
  if (!$response = json_decode(quizlet_api_request($url, $token), TRUE)) {
    drupal_set_message(t("Cannot communicate with server"), 'error');
    return $backlink;
  }
  else {
    $rows = array();
    $header  = array();
    foreach ($response['terms'] as $key => $value) {
      $row = array();
      foreach ($value as $k => $v) {
        if ($k == 'image') {
          if ($v['url']) {
            $row[] = '<img src="'. $v['url'].'" height="'. $v['height'].'" width="'. $v['width'] .'">';
          }
          else {
            $row[] = '';
          }
        }
        else {
          $row[] = $v;   
        }
      }
      $rows[] = $row;
    }
    return theme_render_template(
            drupal_get_path('module', 'quizlet') .'/templates/quizlet_list.tpl.php', 
            array(
             'title' => $response['title'],
             'description' => $response['description'],
             'term_count' => $response['term_count'],
             'terms' => theme('table', $header, $rows),
             'backlink' => $backlink,
             'savelink' => $savelink 
           ));
   }  
}
/**
* Save quizlet group lists
* 
* @param mixed $id
*/
function quizlet_group_terms_save($id) {
  global $user;
  $key = variable_get('quizlet_api_key', ''); 
  $token = variable_get('quizlet_access_token', '');
  $url = 'https://api.quizlet.com/2.0/sets/'. $id .'?client_id='. $key .'&extended=on&whitespace=off';
  if (!$response = json_decode(quizlet_api_request($url, $token), TRUE)) {
    drupal_set_message(t("Cannot communicate with server"), 'error');
    drupal_goto('quizlet/group', 'group_id='. $_GET['group_id']);
  }
  else {
    $nid = db_result(db_query("select nid from {quizlet_private_lists} where quizlet_id='%d'", $id));
    if ($nid && !variable_get('quizlet_multiple_copy', '')) {
      $node = node_load($nid);
      $node->changed = time();
      $node->title = htmlspecialchars_decode($response['title'], ENT_QUOTES);
      $node->body = $response['description'];
      $node->quizlet_data = serialize($response['terms']);
      $node->quizlet_id = $id;
      node_save($node);
      drupal_set_message(t('Quizlet private list updated successfully.'));
    }
    else {
      $node = new stdClass();
      $node->type = 'quizlet_private';
      $node->status = 1;
      $node->uid = $user->uid;
      $node->created = time();
      $node->changed = time();
      $node->title = htmlspecialchars_decode($response['title'], ENT_QUOTES);
      $node->body = $response['description'];
      $node->quizlet_data = serialize($response['terms']);
      $node->quizlet_id = $id;
      node_save($node);
      drupal_set_message(t('Quizlet private list saved successfully.'));  
    }
    drupal_goto('node/'. $node->nid);  
  }
}